package com.green.study.bean;

import com.google.gson.annotations.SerializedName;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USER_INFO".
 */
public class UserInfo {

    /** Not-null value. */
	@SerializedName("USER_NAME")
    private String userName;
    /** Not-null value. */
	@SerializedName("USER_PASSWORD")
    private String userPassword;
    /** Not-null value. */
	@SerializedName("USER_ID")
    private String userId;
	@SerializedName("USER_ADDRESS")
    private String userAddress;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserInfo() {
    }

    public UserInfo(String userId) {
        this.userId = userId;
    }

    public UserInfo(String userName, String userPassword, String userId, String userAddress) {
        this.userName = userName;
        this.userPassword = userPassword;
        this.userId = userId;
        this.userAddress = userAddress;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public String getUserPassword() {
        return userPassword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserAddress() {
        return userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
